### ISSUE TITLE
google api

### ISSUE THREAD

**Issue by ghost** [likedan/WeatherAroundUs-NEW#1]
Hi, How to set up google api?

**Comment by Tedko** [comment]
first make sure you are using the '/WeatherAroundUs/WeatherMap.xcworkspace'

The google bundles shoule be already included:
![2015-05-11 4 07 59](https://cloud.githubusercontent.com/assets/6687437/7561639/52e2c76e-f793-11e4-92d9-561f489b4363.png)

**Comment by Tedko** [comment]
Note that we had just slightly updated an issue with map. But it should not affect Google's APIs

**Comment by ghost** [comment]
And here?
https://console.developers.google.com/project

**Comment by Tedko** [comment]
@likedan

**Comment by likedan** [comment]
https://code.google.com/apis/console

**Comment by Tedko** [comment]
add it to the wiki
